config/routes.rb
Rails.application.routes.draw do
  get "/auth/tumblr", as: "tumblr_login"
  get "/auth/tumblr/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:show, :index]

  root to:  "home#index"
  post "/", to: "home#update"
end

app/models/blog.rb
class Blog
  attr_reader :blog_name, :current_user

  def initialize(current_user)
    @blog_name = current_user.uid
    @current_user = current_user
  end

  def title
    info(blog_name)[:title]
  end

  def total_posts
    info(blog_name)[:total_posts]
  end

  def avatar
    get_avatar(blog_name)
  end

  def posts
    posts = get_posts(blog_name)
    post_content = posts.map do |post|
      [post[:title], post[:body].gsub("<p>", "").gsub("</p>", "")]
    end
  end

  def photos
    photos = get_photos(blog_name).map{|post| {:summary => post[:summary], :photos => post[:photos].map{|photo| photo[:alt_sizes][1][:url]}}}
  end

  def following
    blogs = get_names(current_user)["blogs"]
    names = blogs.map do |blog|
      blog["name"]
    end.first(8)
  end

  def following_photos(name)
    photos = (get_photos(name).map{|post| {summary: post[:summary], post_id: post[:id], reblog_key: post[:reblog_key], photos: post[:photos].map{|photo| photo[:alt_sizes][1][:url]}}}).first
  end

  def like(params)
    TumblrService.new.like(current_user, params)
  end

  def reblog(params)
    TumblrService.new.reblog(current_user, params)
  end

  private

  def info(blog_name) #took out self
    TumblrService.new(blog_name).info
  end

  def get_avatar(blog_name)
    TumblrService.new(blog_name).avatar
  end

  def get_posts(blog_name)
    TumblrService.new(blog_name).posts
  end

  def get_photos(blog_name)
    TumblrService.new(blog_name).photos
  end

  def get_names(current_user)
    TumblrService.new(blog_name).following(current_user)
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid = auth_info.uid
      new_user.name = auth_info.extra.raw_info.name
      new_user.oauth_token = auth_info.credentials.token #there is no screename
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to root_path unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user
      @following = Blog.new(current_user).following
    end
  end

  def update
    if params[:method] == "like"
      like_post = Blog.new(current_user).like(blog_params)
      flash[:notice] = "you liked a post! <3"
      redirect_to root_path
    elsif params[:method] == "reblog"
      Blog.new(current_user).reblog(blog_params)
      flash[:notice] = "you reblogged a post! <3"
      redirect_to root_path
    end
  end

  private

  def blog_params
    params.permit(:post_id, :reblog_key)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:index]
  def index

  end

  def show
    @blog = Blog.new(current_user)
  end
end



# Build a basic version of the Tumblr UI. As a user, I should be able to:
#
# Authenticate with my Tumblr account
# See my basic profile information (username, profile pic)
# View a list of recent posts from my feed
# View embedded photo or video content for the posts
# Favorite a post
# Reblog a post

app/helpers/application_helper.rb
module ApplicationHelper
  def new_blog(name)
    Blog.new(current_user).following_photos(name)
  end
end

app/views/home/index.html.erb
<h1>Feed</h1>

<div class="container">

  <% if current_user %>
    <div class="row">
       <div class="col s12 m7">
         <% @following.each do |name| %>
          <%post = new_blog(name) %>
            <div id="<%=name%>">
             <div class="card blue-grey darken-1">
               <% post[:photos].each do |url| %>
                 <div class="card-image">
                   <%= image_tag("#{url}") %>
                 </div>
                <% end %>
                 <div class="card-content">
                   <p><%= name %></p>
                   <p><%= post[:summary] %></p>
                    <%= button_to "like", {controller: "home", action: "update", method: "like", post_id: post[:post_id], reblog_key: post[:reblog_key]} %>
                    <%= button_to "reblog", {controller: "home", action: "update", method: "reblog", post_id: post[:post_id].to_i, reblog_key: post[:reblog_key]} %>
                </div>
             </div> <br><br>
          </div>
        <% end %>
      </div>
    </div>
    <% else %>
    <h4>Please log in to see your feed</h4>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiCurious</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "shared/nav_bar" %>

<div class="container">
  <% flash.each do |type, message| %>
    <div class="<%= type %>">
      <%= raw(message)%>
    </div>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/shared/_nav_bar.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">Tumblrd</a>
    <ul class="right hide-on-med-and-down">
      <% if current_user %>
        <li><%= link_to "#{current_user.name}", user_path(current_user) %> </li>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign in with Tumblr", tumblr_login_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/index.html.erb
<div class="container">
  <h1><%= current_user.name %></h1>

  <div class="row">
    <div class="col s12 offset-s3">
      <%= image_tag("http://40.media.tumblr.com/f4c8cde461f53b4aaef4451fc247f30a/tumblr_my0xm6LBsX1qdzaxuo1_400.jpg") %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1><%= current_user.name %></h1>


  Title: <%= @blog.title %><br>
  Total Posts: <%= @blog.total_posts %><br><br>

  <div class="row">
    <div class="col s12">
      <img src="data:image/png;base64,<%= @blog.avatar %>" />
    </div>
  </div>

   <div class="row">
       <div class="col s12 m6">
         <% @blog.posts.each do |post| %>
           <div class="card blue-grey darken-1">
             <div class="card-content white-text">
               <span class="card-title"><%= post[0] %></span>
               <p><%= post[1] %></p>
             </div>
           </div>
         <% end %>
       </div>
     </div>

    <div class="row">
     <div class="col s12 m7">
       <% @blog.photos.each do |post| %>
         <div class="card blue-grey darken-1">
           <% post[:photos].each do |url| %>
             <div class="card-image">
               <%= image_tag("#{url}") %>
             </div>
            <% end %>
             <div class="card-content">
               <p><%= post[:summary] %></p>
            </div>
         </div>
        <% end %>
     </div>
   </div>

</div>